### ISSUE TITLE
Failed to close the XContentBuilder

### ISSUE THREAD

**Issue by 478682649** [Redliver/flume-ng-elasticsearch5-sink#1]
When I build this ,flume start not any errors, but when processing.... there is a error :

10 Jan 2017 14:16:27,920 ERROR [SinkRunner-PollingRunner-DefaultSinkProcessor] (com.frontier45.flume.sink.elasticsearch2.ElasticSearchSink.process:208)  - Failed to close the XContentBuilder
10 Jan 2017 14:16:27,920 ERROR [SinkRunner-PollingRunner-DefaultSinkProcessor] (com.frontier45.flume.sink.elasticsearch2.ElasticSearchSink.process:208)  - Failed to close the XContentBuilder
10 Jan 2017 14:16:27,920 DEBUG [SinkRunner-PollingRunner-DefaultSinkProcessor] (com.frontier45.flume.sink.elasticsearch2.ElasticSearchSink.process:167)  - processing...

what's wrong with this???

**Comment by Redliver** [comment]
Can you pass the test case  TestElasticSearchDynamicSerializer.testRoundTrip
```
 XContentBuilder actual = fixture.getContentBuilder(event);
   System.out.println(expected.bytes().utf8ToString());
   System.out.println(actual.bytes().utf8ToString());
```
