### ISSUE TITLE
源码与Jar文件不相符问题

### ISSUE THREAD

**Issue by LiushuiXiaoxia** [Redliver/flume-ng-elasticsearch5-sink#2]
ElasticSearchLogStashEventSerializer.java 文件

128行
```java
    builder.startObject("@fields");
    for (String key : headers.keySet()) {
      byte[] val = headers.get(key).getBytes(charset);
      ContentBuilderUtil.appendField(builder, key, val);

```
包含这几行代码，但是我反编译maven上面的jar文件，发现没有这几行代码，使用maven上的jar是可以与es5继承的，但是如果包含了上面的代码，则不行。

**Comment by Redliver** [comment]
我试了下反编译maven 仓库1.6和1.7 版本的flume-ng-elasticsearch-sink，是有上面的代码的，具体也可以查看官方源码文件 
官网：https://flume.apache.org/source.html
源码地址：https://git-wip-us.apache.org/repos/asf?p=flume.git;a=tree;h=refs/heads/trunk;hb=trunk

1.6版本官方提供的默认的jar 是不支持ES5.0 以上的，主要得对一些API 和依赖进行升级，应该和你这里提到的这个文件关系不大。
